name: kareeb
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version information.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies
dependencies:
  adhan: ^2.0.0+1
  audioplayers: ^6.1.0
  cloud_firestore: ^5.5.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  hijri: ^3.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  just_audio: ^0.9.42
  location: ^7.0.1
  shared_preferences: ^2.3.3
  solid_bottom_sheet: ^0.1.13
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# Flutter-specific settings.
flutter:
  uses-material-design: true

  # Asset configuration
  assets:
    - assets/images/

  # Custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
