name: kareeb
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version information.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies
dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# Flutter-specific settings.
flutter:
  uses-material-design: true

  # Asset configuration
  assets:
    - assets/images/

  # Custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          style: italic
